### ISSUE TITLE
File not found: master/lib/main.js

### ISSUE THREAD

**Issue by lissy93** [pratikmallya/autolabeler-codeowners#10]
Hey @pratikmallya 

This looks like it could be a really useful action :) I tried to set it up on one of my repos, but when running it, I get the following error:
```
Error: File not found: '/home/runner/work/_actions/pratikmallya/autolabeler-codeowners/master/lib/main.js'
```

Is this something that I am doing wrong, or maybe a bug?

For reference, here is [the build log](https://github.com/Lissy93/dashy/runs/3269674925) and my [action YAML file](https://github.com/Lissy93/dashy/blob/61a3e6ba54996c098a5e672476b3dc28533f5997/.github/workflows/assign-reviewer.yml). I've double-checked that my token is correct, and my `.github/CODEOWNERS` file is present.

Thanks very much :)
Alicia

---

![image](https://user-images.githubusercontent.com/1862727/128603667-106f5907-9812-480f-a1e5-0486462705ba.png)

**Comment by pratikmallya** [comment]
Hey @Lissy93, could you try switching to `release/v1` from master in the action yaml file? i.e. [change](https://github.com/Lissy93/dashy/blob/61a3e6ba54996c098a5e672476b3dc28533f5997/.github/workflows/assign-reviewer.yml#L11)

```
uses: pratikmallya/autolabeler-codeowners@master
```
to 
```
uses: pratikmallya/autolabeler-codeowners@releases/v1
```
and try again?

I [updated the readme](https://github.com/pratikmallya/autolabeler-codeowners/pull/12) to specify the correct branch, thanks for reporting this! Lmk if that works

**Comment by lissy93** [comment]
Awesome, thanks very much - that fixed it for me :)

**Comment by lissy93** [comment]
I noticed that as well as assigning the reviewer, the action also applies a tag to each PR with the users. Is this something that GitHub does automatically, or is there any way I can turn this off?

Since I don't like having too many tags cluttering up the Issues search, so don't want there to then be a tag for ever user in the owners file as well.
![image](https://user-images.githubusercontent.com/1862727/128612223-d4762b0e-2966-4429-9e38-caabe0c8dda9.png)

**Comment by pratikmallya** [comment]
> I noticed that as well as assigning the reviewer, the action also applies a tag to each PR with the users. Is this something that GitHub does automatically, or is there any way I can turn this off? 
> Since I don't like having too many tags cluttering up the Issues search, so don't want there to then be a tag for ever user in the owners file as well.

The current algorithm is:
- check if a label corresponding to codeowner exists, if not create it

What do you think should the ideal behavior look like? Would you like it to ignore user-level codeowners and just tag with team-level codeowners? Or should there be a setting that just disables creation of labels, so it would use a label only if it was already present?

**Comment by lissy93** [comment]
Ah I see, thanks for explaining that, makes sense

I guess I was expecting the action to assign reviewers, but did not want the creation of labels- As PRs can be searched by reviewers, the same was they can with labels, so I don't know what additional benefit labels has.

Maybe a possible idea for a future update could be to add a parameter to make the tags optional. It's pretty low priority through, as the action works fine as is.

**Comment by pratikmallya** [comment]
> I guess I was expecting the action to assign reviewers, but did not want the creation of labels- As PRs can be searched by reviewers, the same was they can with labels, so I don't know what additional benefit labels has.

That's right, PR's can be natively searched by reviewers, but not by github teams. The purpose of this action was to enable codeowning github teams to quickly know which open PR's were assigned to them in a monorepo (where there could be several different codeowning teams). 

I do agree it doesn't make much sense to label with a reviewer, though. Let me see if I can restrict it to just teams.

 > Maybe a possible idea for a future update could be to add a parameter to make the tags optional. It's pretty low priority through, as the action works fine as is.

Just so we're on the same page, you're saying that the label _creation_ should be optional, correct?
